### PR TITLE
SAP cloud logging support migration to SB 3.x

### PR DESCRIPTION
**Pull request by aamotharald**
this migrates SAP's cloud foundry based java logging support libraries to SB 3.x

## What's changed?
SAP's cloud foundry based logging support on jakarta
See https://github.com/SAP/cf-java-logging-support/

## What's your motivation?
make SB 3.x migrations with SAP and partner code easier

## Anything in particular you'd like reviewers to focus on?
Questions:
- Does org.openrewrite.java.dependencies.ChangeDependency take care of maven AND gradle?
- I ONLY want to change the artifactId, NOT the groupId and the version or anything else - Does that fit?
- I saw no tests in this repo for pom.xml files, so I assume tests are in rewrite-maven/rewrite-gradle?
- Does this step ONLY kick in if the dependency com.sap.hcp.cf.logging:cf-java-logging-support-servlet:<someVersion> is present?
- Is this the right location to put the recipe in?
- The Mr. Monk in me did some formatting - is that OK?

### Checklist
- [ ] I've added unit tests to cover both positive and negative cases
- [x] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by aamotharald** [comment]
Hi @sambsnyd @timtebeek ,
my first contribution to openRewrite - I'm excited..
Of course the contribution is SAP-flavoured :-)

**Comment by timtebeek** [comment]
> Hi @sambsnyd @timtebeek , my first contribution to openRewrite - I'm excited.. Of course the contribution is SAP-flavoured :-)

Great to see @aamotharald ! I've added a small change to add a version range, after spotting that the jakarta module was only added in 3.7.0: https://github.com/SAP/cf-java-logging-support/commit/c8f4f2a21705e955be82dac7ddbc41f53f38700b. Otherwise folks coming from older version might end up with a non-existing `cf-java-logging-support-servlet-jakarta:3.6.0` for instance. The range should resolve to whatever is the latest version at the time of release.

**Review by timtebeek — APPROVED** [review]

**Comment by aamotharald** [comment]
Thank's for checking the version @timtebeek  .
With regards to the version I was still checking back with @KarstenSchnitter , but looks like you did dig out the version where the jakarta module got added :-) Thanks a lot!

**Comment by KarstenSchnitter** [comment]
Looks all good to me. You got the right version as can be seen in the [release notes of v3.7.0](https://github.com/SAP/cf-java-logging-support/releases/tag/v3.7.0).

**Pull request merged**
