### PR TITLE
feat: Upgrade to Spring Boot 3.2, and Virtual Threads if on Java 21

### PR DESCRIPTION
**Pull request by SimonVerhoeven**
## What's changed?

A new recipe to enable VT in case the upgrade is for a Java 21 project.

## What's your motivation?

To facilitate the adaptation of Virtual Threads

## Anything in particular you'd like reviewers to focus on?

There's no org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2 recipe yet, but I wanted to keep that for a standalone PR.

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've added the license header to any new files through `./gradlew licenseFormat`
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by timtebeek** [comment]
There's likely to be some conflicts with the PR I just created
- https://github.com/openrewrite/rewrite-spring/pull/445 

We should indeed create a separate 3.2 migration recipe, and have that ready (and ideally documented) before next Thursday's release.

**Comment by SimonVerhoeven** [comment]
Seems likely, I'll keep an eye on that one and update this one based on that one.

**Comment by SimonVerhoeven** [comment]
The latest commit restores `spring-boot-32.yml`, and also adds the actual migration recipe.
This does mean it now also has a dependency on #447

**Review by timtebeek — APPROVED** [review]

**Comment by timtebeek** [comment]
Great work once again @SimonVerhoeven ! Thanks a lot for kicking off the Spring Boot 3.2 migration recipes & virtual thread adoption.

**Pull request merged**
