### PR TITLE
Upgrade Gradle wrapper and Spring Gradle plugins

### PR DESCRIPTION
**Pull request by shanman190**

### CODE REVIEW

**Comment by shanman190** [comment]
Fixes gh-374.

**Review by sambsnyd — APPROVED** [review]
Thanks! Looks like the build is complaining about missing license headers

**Comment by shanman190** [comment]
So fixed those. The present failure appears to be an OOM with classgraph. Do you have any thoughts on how you'd like to proceed with that one?

**Comment by timtebeek** [comment]
I think we'd need a release of openrewrite/rewrite to pick up https://github.com/openrewrite/rewrite/commit/65d4c7341810a6013f93a6efeb506f82521ddcbf , since we depend on a snapshot there, which the release then pins down the latest release.

**Comment by shanman190** [comment]
Yeah, these changes will be dependent upon that commit. I don't see anything wrong with releasing rewrite proper though.

**Pull request merged**
